name: IOT IJK ANDROID DEBUG CI

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
  pull_request:
    branches: [ master ]

env:
  IOT_SONATYPE_USERNAME: ${{ secrets.IOT_SONATYPE_USERNAME }}
  IOT_SONATYPE_PASSWORD: ${{ secrets.IOT_SONATYPE_PASSWORD }}
  GPG_DECRYPT_PASSPHRASE: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download r10e NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r10e-darwin-x86_64.zip
          unzip android-ndk-r10e-darwin-x86_64.zip
      - name: Update SDK Version
        run: bash .github/script/updateVersionForSnapshot.sh
      - name: Build with Gradle
        run: |
          export ANDROID_NDK=/Users/runner/work/iot-ijkplayer/iot-ijkplayer/android-ndk-r10e
          sh .github/script/build_armv7a.sh
          cd android/ijkplayer
          ./gradlew :ijkplayer-armv7a:assemble
          ./gradlew :ijkplayer-arm64:assemble
          ./gradlew :ijkplayer-java:assemble
      - name: Publish aar to Maven
        run: |
          cd android/ijkplayer
          ./gradlew :ijkplayer-armv7a:publish
          ./gradlew :ijkplayer-arm64:publish
          ./gradlew :ijkplayer-java:publish
